/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  sidebar: [
    'intro',
    'architecture',
    {
      'Getting Started': [
        'getting-started/index',
        'getting-started/configuration',
        'getting-started/running-locally',
        'getting-started/testing'
      ]
    },
    {
      'Deployment': [
        'deployment/index',
      ]
    },
    {
      'Authorizer': [
        'authorizer-guide/overview',
        'authorizer-guide/authz',
        'authorizer-guide/identity-context',
        'authorizer-guide/resource-context',
        'authorizer-guide/policy-context',
        'authorizer-guide/is',
        'authorizer-guide/decisiontree',
        'authorizer-guide/query',
        'authorizer-guide/display-state-map',
      ]
    },
    {
      'Directory': [
        'directory/index',
        'directory/define-domain-model',
        'directory/creating-instances',
        'directory/loading-identities'
      ]
    },
    {
      'Policies': [
        'policies/index',
        'policies/registries'
      ]
    },
    {
      'SDKs': [
        'software-development-kits/index',
      ]
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
