name: Update search index

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v4
      - 
        name: Read Configuration
        uses: hashicorp/vault-action@v3
        id: vault
        with:
          url: https://vault.eng.aserto.com/
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/algolia  "API_KEY"          | API_KEY;
            kv/data/algolia  "APPLICATION_ID"   | APPLICATION_ID;
      - 
        name: Run Algolia Scrape
        run: |
          docker run --rm -e "APPLICATION_ID=${APPLICATION_ID}" -e API_KEY="${API_KEY}" -e "CONFIG=$(cat ./scripts/algolia-config.json)" algolia/docsearch-scraper